config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :pledges
  end

  resources :users

  get "profile" => "users#profile", as: 'profile'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :backer, class_name: 'User', foreign_key: 'backer_id'
  belongs_to :project

  # validates :amount, presence: true
  validates :amount, numericality: { greater_than: 0, only_integer: true }

end
	

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards
  has_many :pledges
  has_many :backers, through: :pledges, class_name: 'User'
  belongs_to :owner, class_name: 'User'
  accepts_nested_attributes_for :rewards

  def amount_raised
  	sum = 0
  	pledges.each do |pledge|
  		sum = sum + pledge.amount
  	end
  	return sum
  end

  def project_funded
  end


  



  def self.available_categories
  	%w(Music Games Household Video Art Outdoors Technology Food Sports Clothing Automotive Lifehack Business )
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :owned_projects, class_name: 'Project', foreign_key: 'owner_id'
  has_many :pledges, foreign_key: 'backer_id'
  has_many :rewards, through: :pledges, source: :backer
  has_many :projects, through: :pledges

  validates :password, length: { minimum: 8 }
  validates :password, confirmation: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception	
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

	def create
		@project = Project.find(params[:project_id])
		# project.pledges.create(params[:pledge])

		@pledge = Pledge.new(pledge_params)
		@pledge.project = @project
		@pledge.backer = current_user

		respond_to do |format|
			if @pledge.save
				format.html { redirect_to project_path(@project) }
				format.js {}
			else
				format.html { render 'new'}
				format.js
			end																							 

		end
	end

	private
	def pledge_params
		params.require(:pledge).permit(:amount, :project_id, :backer_id)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
    if params[:search]
      @projects = Project.where("LOWER(title) LIKE LOWER(?)", "%#{params[:search]}%")
    else
		  @projects = Project.all
	  end

    respond_to do |format|
      format.html do
        if params[:autocomplete]
          @projects = @projects.limit(10)
          render partial: "autocomplete"
        else
          render
        end
      end
      format.js
    end
  end

	def show
		@project = Project.find(params[:id])
		@pledge = Pledge.new

	end

	def new
		if current_user
			@project = Project.new
			3.times { @project.rewards.build }
			@project.start_date = Date.today

		else
			redirect_to login_path
		end
	end

	def create
		@project = Project.new(project_params)
		
		if @project.save
      redirect_to projects_url
    else
      render :new
    end
  end

  def destroy
  	if current_user
	  	@project = Project.find(params[:id])
	    @project.destroy
    	redirect_to projects_url
    else
    	redirect_to login_path
    end
  end


	private
	def project_params
		params.require(:project).permit(
			:title,
			:description,
			:funding_goal,
			:start_date,
			:end_date,
			:category,
			rewards_attributes: [:description, :amount])
	end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid."
      render new
    end
  end

  def destroy
	  logout
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def profile
		@user = current_user
		render :show
	end

	def create
		@user = User.new(user_params)

		if @user.save
			auto_login(@user)

			redirect_to projects_url
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def days_in_future_for_select(n)
		options = (0..10).map do |n| 
			d = Time.now + n.days
			label = d.strftime("%A, %d %b %Y")
			value = d.strftime("%Y-%m-%d")
			[label, value] 
		end

		options_for_select(options)
	end
	
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p class="userinfo">
	<% if current_user %>
	Signed in as <%= current_user.first_name %>. <%= link_to "Log out", logout_path %>
	<% else %>
	<%= link_to "Log in", login_path %> or <%= link_to "Sign up", signup_path %>
	<% end %>
</p>
<p>
	|&nbsp;<%= link_to "Home", projects_path %>&nbsp;|&nbsp;
	<%= link_to "My Profile", profile_path if current_user %>&nbsp;|
</p>
</body>
</html>

app/views/pledges/create.js.erb
$('ol#backers').append("<li><%= current_user.first_name %></li>");

app/views/projects/_autocomplete.html.erb
<% @projects.each do |project| %>
  <li>
    <%= link_to project.title, project_path(project) %>
  </li>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<!--   <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  -->


  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
    <div class="field">
    <%= f.label :funding_goal %><br />
    <%= f.text_field :funding_goal %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_field :start_date %>
  </div>
  <div class="field">
  <%= f.label :end_date %><br />
  <%= f.date_field :end_date %>
  </div>
    <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, Project.available_categories %>
  </div>
  <h4>Pledge Rewards</h4>
  <div id="rewards">
    <%= link_to_add_association 'Add a Reward', f, :rewards %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<li><%= link_to(project) do %>
		<p><%= project.title %> - <%= project.funding_goal %> </p>			
<% end %>
<p><%= truncate(project.description, length: 100) %></p>

app/views/projects/_reward.html.erb
<h4><%= reward.description %></h4>
	<p>Pledge required: $<%= reward.amount %></p>

app/views/projects/_reward_fields.html.erb
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
<div>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
</div>

app/views/projects/index.html.erb
<h1>WELCOME TO CROWDFUNDER</h1>



<%= link_to "| Add a New Project |", "/projects/new" %>

<%= form_tag projects_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search], autocomplete: "off" %>
  <div id="autocomplete"></div>
  <%= submit_tag "Search" %>
<% end %>


<div id="projects">
  <ul class="projects-list">
		<% @projects.each do |p| %>
			<li>
				<%= link_to(p) do %>
		  		<%= p.title %>
				<% end %>
		 	</li>
	 	<% end%>
	</ul>
</div>

app/views/projects/index.js.erb
$('#projects').html("<%= j(render @projects) %>");

app/views/projects/new.html.erb
<h1>Get your project funded!</h1>


<%= render 'form' %>


  <h4>---------------</h4>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1>Currently viewing "<%= @project.title %>"</h1>
<p>We need to raise: $<%= @project.funding_goal %> CAD</p>
<p>Category: <%= @project.category %></p>
<p><%= @project.description %></p>
<p>Time Left <%= time_ago_in_words(@project.end_date) %></p>
<p>Amount raised to date <%=  number_to_currency(@project.amount_raised) %></p>

<h2>Rewards for this Project</h2>
<%= render partial: 'reward', collection: @project.rewards %>

<h2>Backers of this Project</h2>
<ol id="backers">
<% @project.backers.each do |backer|%>

	<li><%= backer.first_name %></li>
		
	

<% end %>
</ol>
<div id="pledge">
	
</div>

<% if @pledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

      <ul>
      <% @pledge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<%= form_for([@project, @pledge], remote: true) do |f| %>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>

  </div>
    <div class="actions">
    <%= f.submit value: "Donate" %>
  </div>
<% end %>

<%= link_to "Delete This Project", @project, method: :delete, data: {confirm: "Are you sure you want to delete this project?"}  %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@user.errors.count, "error") %> Prohibited you from creating a user</h2>
			<ul>
				<% @user.errors.full_messages.each do |m| %>
				<li><%= m %></li>
			</ul>
			<% end %>
		</div>
		<% end %>
	<div class="feild">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
		</div>

		<div class="feild">
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
		</div>

		<div class="feild">
		<%= f.label :email %>
		<%= f.text_field :email %>
		</div>

		<div class="feild">
		<%= f.label :password %>
		<%= f.password_field :password %>
		</div>

		<div class="feild">
		<%= f.label :password_confirmation%>
		<%= f.password_field :password_confirmation %>
		</div>

		<%= f.submit %>
	<% end %>

app/views/users/show.html.erb
<h1>Hello, <%= @user.first_name %>! Welcome to your Crowdfunder profile page.</h1>

<h1>Your projects</h1>

<li>
	<% @user.owned_projects.each do |p| %>
		<li><%= p.title %></li>
	<% end %>
</li>


<h1>Projects you've backed</h1>

<li>
	<% @user.projects.each do |p| %>
		<li><%= p.title %></li>
	<% end %>
</li>